import checkoutE2eTimeout from './showcase-media/checkout-e2e-timeout.webm';
import checkoutFixed from './showcase-media/checkout-fixed.png';
import checkoutTotalZero from './showcase-media/checkout-total-zero.png';
import ciRunnerMemory from './showcase-media/ci-runner-memory.png';
import intentV2Diff from './showcase-media/intent-v2-diff.png';
import iosCartTotal from './showcase-media/ios-cart-total.png';
import ledgerLatency from './showcase-media/ledger-latency.png';
import voiceoverTotal from './showcase-media/voiceover-total.ogg';
import { showcaseMediaFile } from './showcase';

/**
 * URLs of the showcase scenario's bundled media, by file name. Generated by
 * `scripts/showcase-media.mjs`; Vite emits them as static assets, and only
 * into the dev-only showcase chunk.
 */
const ASSETS: Readonly<Record<string, string>> = {
  'checkout-e2e-timeout.webm': checkoutE2eTimeout,
  'checkout-fixed.png': checkoutFixed,
  'checkout-total-zero.png': checkoutTotalZero,
  'ci-runner-memory.png': ciRunnerMemory,
  'intent-v2-diff.png': intentV2Diff,
  'ios-cart-total.png': iosCartTotal,
  'ledger-latency.png': ledgerLatency,
  'voiceover-total.ogg': voiceoverTotal,
};

/** URL of a showcase media item's bundled asset, or undefined for any other ID. */
export function showcaseMediaUrl(mediaId: string): string | undefined {
  const file = showcaseMediaFile(mediaId);
  return file ? ASSETS[file] : undefined;
}
